game: 
	$(CC) main.c modes.c saveImage.c manageGenerations.c createNew.c helpCreate.c neighbor.c -Wall -pedantic -o game

runsbs:
	./game --in plik.txt --out wunik.txt -s o3 -n 10 --how Ms -m sbs 
runfast: 
	./game --in plik.txt --out wunik.txt -s f2 -n 10 --how Ms -m fast
