game: 
	$(CC) main.c modes.c saveImage.c manageGenerations.c createNew.c helpCreate.c neighbor.c -Wall -pedantic -o game

runsbs:
	./game --in simkinGun.txt --out output.txt -s f5 -n 200 --how Ms -m fast 
runfast: 
	./game --in plik.txt --out wunik.txt -s f2 -n 10 --how Ms -m fast
